### ISSUE TITLE
Rails 5.1 "Use at least 255 characters"

### ISSUE THREAD

**Issue by simonhutchings** [plataformatec/simple_form#1496]
Every input_field I add to a form which is a thing field gets the above error on submit.

Have no idea why as was working ok before and can't think what I might have added to cause it. Anyone seen this issue?

Hutch

**Comment by simonhutchings** [comment]
An update must have caused it but this fixed it

```
  config.wrappers :default, class: :input, hint_class: :field_with_hint, error_class: :field_with_errors do |b|
    ## Extensions enabled by default
    # Any of these extensions can be disabled for a
    # given input by passing: `f.input EXTENSION_NAME => false`.
    # You can make any of these extensions optional by
    # renaming `b.use` to `b.optional`.

    # Determines whether to use HTML5 (:email, :url, ...)
    # and required attributes
    b.use :html5

    # Calculates placeholders automatically from I18n
    # You can also pass a string as f.input placeholder: "Placeholder"
    b.use :placeholder

    ## Optional extensions
    # They are disabled unless you pass `f.input EXTENSION_NAME => true`
    # to the input. If so, they will retrieve the values from the model
    # if any exists. If you want to enable any of those
    # extensions by default, you can change `b.optional` to `b.use`.

    # Calculates maxlength from length validations for string inputs
    # and/or database column lengths
    b.optional :maxlength

    # Calculate minlength from length validations for string inputs
    b.optional :minlength

    # Calculates pattern from format validations for string inputs
    b.optional :pattern

    # Calculates min and max from length validations for numeric inputs
    b.optional :min_max

    # Calculates readonly automatically from readonly attributes
    b.optional :readonly

    ## Inputs
    b.use :label_input
    b.use :hint,  wrap_with: { tag: :span, class: :hint }
    b.use :error, wrap_with: { tag: :span, class: :error }
  end
```

**Comment by simonini** [comment]
I have same problem

**Comment by simonhutchings** [comment]
Just add the stuff above into the file config/initializers/simple_format.rb adjust if needed, solved the problem straight away as it makes everything optional

**Comment by Jecko-o** [comment]
The problem updating is solved just running a fresh `rails generate simple_form:install, if you don't mind for your previous customization.

**Comment by feliperenan** [comment]
It seems like resolved. I going to close this issue, you can open a new issue if necessary.

**Comment by mameier** [comment]
This is not really fixed.
A new install simply declares **minlength** as optional and thereby disables it.
minlength is still broken.
The fix is described in #1531
